name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, Compile, Test, Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (if available)
        run: |
          if npm run | grep -q " lint"; then
            npm run lint
          else
            echo "No lint script found — skipping."
          fi

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests (with coverage if available)
        run: |
          if npm run | grep -q " coverage"; then
            npm run coverage
          else
            npx hardhat test
          fi

      - name: Upload coverage report (if generated)
        if: ${{ hashFiles('coverage/**') != '' || hashFiles('coverage.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/**
            coverage.json
          if-no-files-found: ignore

  slither:
    name: Static Analysis (Slither)
    runs-on: ubuntu-latest
    needs: build-test
    # Don’t block merges if Slither isn’t perfect yet
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node deps (for Hardhat config parsing)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci

      # Runs Slither via official action (handles solc installs)
      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        with:
          target: .
          slither-args: "--filter-paths node_modules --exclude naming-convention,low-level-calls"
          fail-on: "none"   # change to 'medium' or 'high' once you’re ready to enforce

  formatting:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Prettier check (if available)
        run: |
          if npm run | grep -q " prettier:check"; then
            npm run prettier:check
          else
            echo "No prettier:check script — skipping."
          fi
